# Generated by Django 4.2.7 on 2023-11-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=30)),
                ('aboutme', models.TextField()),
                ('myskills', models.CharField(choices=[('Photo', 'Photography'), ('WD', 'Web_Design'), ('Psh', 'Photoshop')], max_length=5)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
